name: Continuous Integration
on: [push]
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - linux-musl
        - linux-gnu
        - macos
        - windows
        include:
        - build: linux-musl
          os: ubuntu-latest
          target: x86_64-unknown-linux-musl
        - build: linux-gnu
          os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
        - build: macos
          os: macOS-latest
          target: x86_64-apple-darwin
        - build: windows
          os: windows-latest
          target: x86_64-pc-windows-msvc
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target ${{ matrix.target }} --manifest-path=symtool/Cargo.toml
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --target ${{ matrix.target }} --manifest-path=symtool/Cargo.toml
